################################################################################
## LIBSTDCXX

if(STATIC_LIBSTDCXX)
  set(EXTRA_CXX_FLAGS_STATIC_LIBSTDCXX "-no-pie")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${EXTRA_CXX_FLAGS_STATIC_LIBSTDCXX}")
  set(EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX "-static -static-libgcc -static-libstdc++")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
  set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${EXTRA_LINKER_FLAGS_STATIC_LIBSTDCXX}")
endif()
